version: '3.4'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER_FILE: /seed/mysql.user
      MYSQL_PASSWORD_FILE: /seed/mysql.pass 
      MYSQL_ROOT_PASSWORD_FILE: /seed/mysql.pass
      MYSQL_DATABASE: adidas_fec
    volumes:
      - type: bind
        source: ./seed
        target: /seed
  reviews:
    build: .
    environment:
      NODE_ENV: production
    depends_on:
        - 'mysql'
    ports:
      - '3003:3003'
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - '8080:8080'

